/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import ClaseDAO.Reserva;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author hegam
 */
public class PrincipalCRUD extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalCRUD
     */
    public PrincipalCRUD() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public PrincipalCRUD(String nombreUsuario) {
        initComponents();
        lblUsuarioName.setText(nombreUsuario);
        this.setLocationRelativeTo(null);
        Reserva.listarReservas(tablaHuesped);
        bloquearCamposUpdate();
    }
    
    private void bloquearCamposUpdate() {
        txtNombre_update.setEnabled(false);
        txtApePater_update.setEnabled(false);
        txtApeMat_update.setEnabled(false);
        txtCorreo_update.setEnabled(false);
        txtNumTel_update.setEnabled(false);
        txtNroHab_update.setEnabled(false);
        cbTipoHab_update.setEnabled(false);
        txtPrecioHab_update.setEnabled(false);
        btnActualizar_update.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuarioName = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDNI_crear = new javax.swing.JTextField();
        txtNombre_crear = new javax.swing.JTextField();
        txtApePater_crear = new javax.swing.JTextField();
        txtApeMat_crear = new javax.swing.JTextField();
        txtCorreo_crear = new javax.swing.JTextField();
        txtNumTel_crear = new javax.swing.JTextField();
        txtNroHab_crear = new javax.swing.JTextField();
        cbTipoHab_crear = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btnRegistrar_crear = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        txtPrecioHab_crear = new javax.swing.JTextField();
        dcEntrada = new com.toedter.calendar.JDateChooser();
        dcSalida = new com.toedter.calendar.JDateChooser();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtDNI_update = new javax.swing.JTextField();
        txtNombre_update = new javax.swing.JTextField();
        txtApePater_update = new javax.swing.JTextField();
        txtApeMat_update = new javax.swing.JTextField();
        txtCorreo_update = new javax.swing.JTextField();
        txtNumTel_update = new javax.swing.JTextField();
        txtNroHab_update = new javax.swing.JTextField();
        cbTipoHab_update = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnBuscar_update = new javax.swing.JButton();
        btnActualizar_update = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtPrecioHab_update = new javax.swing.JTextField();
        dcSalida_update = new com.toedter.calendar.JDateChooser();
        jLabel30 = new javax.swing.JLabel();
        dcEntrada_update = new com.toedter.calendar.JDateChooser();
        jLabel31 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        btnBuscar_update1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHuesped = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtDNI_delete = new javax.swing.JTextField();
        btnRegistrar_crear1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_hotel_marina_128_128.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre Recepcionista");

        lblUsuarioName.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuarioName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarioName.setText("usuario");

        btnCerrarSesion.setBackground(new java.awt.Color(102, 153, 255));
        btnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setToolTipText("");
        btnCerrarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuarioName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarioName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 410));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(102, 153, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Llenar todos los campos para registrar al huésped");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DNI:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Apellido materno:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Apellido paterno:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Tipo de habitación:");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Número de habitación:");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Número telefónico:");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Correo:");

        txtDNI_crear.setBackground(new java.awt.Color(255, 255, 255));
        txtDNI_crear.setForeground(new java.awt.Color(0, 0, 0));

        txtNombre_crear.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre_crear.setForeground(new java.awt.Color(0, 0, 0));

        txtApePater_crear.setBackground(new java.awt.Color(255, 255, 255));
        txtApePater_crear.setForeground(new java.awt.Color(0, 0, 0));

        txtApeMat_crear.setBackground(new java.awt.Color(255, 255, 255));
        txtApeMat_crear.setForeground(new java.awt.Color(0, 0, 0));

        txtCorreo_crear.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo_crear.setForeground(new java.awt.Color(0, 0, 0));

        txtNumTel_crear.setBackground(new java.awt.Color(255, 255, 255));
        txtNumTel_crear.setForeground(new java.awt.Color(0, 0, 0));

        txtNroHab_crear.setBackground(new java.awt.Color(255, 255, 255));
        txtNroHab_crear.setForeground(new java.awt.Color(0, 0, 0));

        cbTipoHab_crear.setBackground(new java.awt.Color(255, 255, 255));
        cbTipoHab_crear.setForeground(new java.awt.Color(0, 0, 0));
        cbTipoHab_crear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HABITACION INDIVIDUAL", "HABITACION DOBLE", "HABITACION TRIPLE", "HABITACION CUADRUPLE", "HABITACION SUITE", "HABITACION PRESIDENCIAL" }));
        cbTipoHab_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoHab_crearActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Disponibilidad desde el 100 hasta el 199");

        btnRegistrar_crear.setBackground(new java.awt.Color(102, 153, 255));
        btnRegistrar_crear.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar_crear.setText("Registrar");
        btnRegistrar_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar_crearActionPerformed(evt);
            }
        });

        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Precio:");

        txtPrecioHab_crear.setBackground(new java.awt.Color(255, 255, 255));

        dcEntrada.setBackground(new java.awt.Color(255, 255, 255));
        dcEntrada.setForeground(new java.awt.Color(255, 255, 255));

        dcSalida.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Fecha de Entrada:");

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Fecha de Salida:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre_crear)
                                    .addComponent(txtApePater_crear)
                                    .addComponent(txtApeMat_crear)
                                    .addComponent(txtCorreo_crear)
                                    .addComponent(txtNumTel_crear)
                                    .addComponent(txtNroHab_crear)
                                    .addComponent(cbTipoHab_crear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrecioHab_crear)
                                    .addComponent(txtDNI_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRegistrar_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(dcEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(dcSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDNI_crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar_crear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre_crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtApePater_crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtApeMat_crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCorreo_crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNumTel_crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNroHab_crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbTipoHab_crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioHab_crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(dcSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear huésped", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Actualizar reserva del huésped a solicitud mediante el DNI");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("DNI:");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Nombre:");

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Apellido paterno:");

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Apellido materno:");

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Correo:");

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Número telefónico:");

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Número de habitación:");

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Tipo de habitación:");

        txtDNI_update.setBackground(new java.awt.Color(255, 255, 255));
        txtDNI_update.setForeground(new java.awt.Color(0, 0, 0));

        txtNombre_update.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre_update.setForeground(new java.awt.Color(0, 0, 0));

        txtApePater_update.setBackground(new java.awt.Color(255, 255, 255));
        txtApePater_update.setForeground(new java.awt.Color(0, 0, 0));

        txtApeMat_update.setBackground(new java.awt.Color(255, 255, 255));
        txtApeMat_update.setForeground(new java.awt.Color(0, 0, 0));

        txtCorreo_update.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo_update.setForeground(new java.awt.Color(0, 0, 0));

        txtNumTel_update.setBackground(new java.awt.Color(255, 255, 255));
        txtNumTel_update.setForeground(new java.awt.Color(0, 0, 0));

        txtNroHab_update.setBackground(new java.awt.Color(255, 255, 255));
        txtNroHab_update.setForeground(new java.awt.Color(0, 0, 0));

        cbTipoHab_update.setBackground(new java.awt.Color(255, 255, 255));
        cbTipoHab_update.setForeground(new java.awt.Color(0, 0, 0));
        cbTipoHab_update.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HABITACION INDIVIDUAL", "HABITACION DOBLE", "HABITACION TRIPLE", "HABITACION CUADRUPLE", "HABITACION SUITE", "HABITACION PRESIDENCIAL" }));
        cbTipoHab_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoHab_updateActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Disponibilidad desde el 100 hasta el 199");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));
        jPanel8.setForeground(new java.awt.Color(0, 0, 0));

        btnBuscar_update.setBackground(new java.awt.Color(102, 153, 255));
        btnBuscar_update.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar_update.setText("Buscar");
        btnBuscar_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar_updateActionPerformed(evt);
            }
        });

        btnActualizar_update.setBackground(new java.awt.Color(102, 153, 255));
        btnActualizar_update.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizar_update.setText("Actualizar");
        btnActualizar_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizar_update, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscar_update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar_update)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Precio:");

        txtPrecioHab_update.setBackground(new java.awt.Color(255, 255, 255));

        dcSalida_update.setBackground(new java.awt.Color(255, 255, 255));

        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Fecha de Salida:");

        dcEntrada_update.setBackground(new java.awt.Color(255, 255, 255));
        dcEntrada_update.setForeground(new java.awt.Color(255, 255, 255));

        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Fecha de Entrada:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dcEntrada_update, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcSalida_update, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre_update)
                                    .addComponent(txtApePater_update)
                                    .addComponent(txtApeMat_update)
                                    .addComponent(txtCorreo_update)
                                    .addComponent(txtNumTel_update)
                                    .addComponent(txtNroHab_update)
                                    .addComponent(cbTipoHab_update, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrecioHab_update)
                                    .addComponent(txtDNI_update, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)))))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtDNI_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtNombre_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtApePater_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtApeMat_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCorreo_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtNumTel_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNroHab_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoHab_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioHab_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcEntrada_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30)
                    .addComponent(dcSalida_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Actualizar huésped", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Se visualizará la lista de huéspedes al momento");

        btnBuscar_update1.setBackground(new java.awt.Color(102, 153, 255));
        btnBuscar_update1.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar_update1.setText("Mostrar lista huéspedes");
        btnBuscar_update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar_update1ActionPerformed(evt);
            }
        });

        tablaHuesped.setBackground(new java.awt.Color(255, 255, 255));
        tablaHuesped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido Pat", "Apellido Mat", "Correo", "Nro Telefono", "Nro Habitacion", "Tipo Hab", "Precio"
            }
        ));
        tablaHuesped.setGridColor(new java.awt.Color(204, 204, 204));
        tablaHuesped.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tablaHuesped);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(btnBuscar_update1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar_update1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar huéspedes", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Elimina huésped solo ingresando su DNI en la casilla de texto");

        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("DNI:");

        txtDNI_delete.setBackground(new java.awt.Color(255, 255, 255));
        txtDNI_delete.setForeground(new java.awt.Color(0, 0, 0));

        btnRegistrar_crear1.setBackground(new java.awt.Color(102, 153, 255));
        btnRegistrar_crear1.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar_crear1.setText("Eliminar");
        btnRegistrar_crear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar_crear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDNI_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrar_crear1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtDNI_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar_crear1))
                .addContainerGap(312, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar huésped", jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 850, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de que quieres cerrar sesión?",
                "Cerrar sesión",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Abrir login de nuevo
            new Login().setVisible(true);
            this.dispose(); // Cierra ventana actual
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnRegistrar_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar_crearActionPerformed
        String dni = txtDNI_crear.getText().trim();
        String nombre = txtNombre_crear.getText().trim();
        String apePater = txtApePater_crear.getText().trim();
        String apeMater = txtApeMat_crear.getText().trim();
        String correo = txtCorreo_crear.getText().trim();
        String telefono = txtNumTel_crear.getText().trim();
        int numHabitacion = Integer.parseInt(txtNroHab_crear.getText().trim());
        String tipoHabitacion = cbTipoHab_crear.getSelectedItem().toString();
        Date entrada = dcEntrada.getDate();
        Date salida = dcSalida.getDate();

        double precio = 0;
        try {
            precio = Double.parseDouble(txtPrecioHab_crear.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número válido.");
            txtPrecioHab_crear.requestFocus();
            return;
        }

        Reserva reserva = new Reserva(
                dni, nombre, apePater, apeMater, correo, telefono, numHabitacion, tipoHabitacion, precio, entrada, salida
        );

        if (reserva.registrar()) {
            limpiarCamposCrear();
        }
    }//GEN-LAST:event_btnRegistrar_crearActionPerformed

    private void btnBuscar_update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar_update1ActionPerformed
        Reserva.listarReservas(tablaHuesped);
    }//GEN-LAST:event_btnBuscar_update1ActionPerformed

    private void btnBuscar_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar_updateActionPerformed
        String dni = txtDNI_update.getText().trim();

        if (dni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un DNI antes de buscar.");
            return;
        }

        Reserva r = Reserva.buscarPorDNI(dni);

        if (r == null) {
            JOptionPane.showMessageDialog(this, "No se encontró una reserva con ese DNI.");
            txtDNI_update.requestFocus();
            bloquearCamposUpdate();
        } else {
            txtNombre_update.setText(r.nombre);
            txtApePater_update.setText(r.apellidoPaterno);
            txtApeMat_update.setText(r.apellidoMaterno);
            txtCorreo_update.setText(r.correo);
            txtNumTel_update.setText(r.telefono);
            txtNroHab_update.setText(String.valueOf(r.numHabitacion));
            cbTipoHab_update.setSelectedItem(r.tipoHabitacion);
            txtPrecioHab_update.setText(String.valueOf(r.precio));
            dcEntrada_update.setDateFormatString(String.valueOf(r.entrada));
            dcSalida_update.setDateFormatString(String.valueOf(r.salida));

            habilitarCamposUpdate();
        }
    }//GEN-LAST:event_btnBuscar_updateActionPerformed

    private void btnActualizar_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar_updateActionPerformed
        String dni = txtDNI_update.getText().trim();
        Date entrada = dcEntrada_update.getDate();  // suponiendo que tienes un JDateChooser
        Date salida = dcSalida_update.getDate();
        
        if (dni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se ha buscado un DNI válido.");
            return;
        }

        try {
            Reserva r = new Reserva(
                    dni,
                    txtNombre_update.getText().trim(),
                    txtApePater_update.getText().trim(),
                    txtApeMat_update.getText().trim(),
                    txtCorreo_update.getText().trim(),
                    txtNumTel_update.getText().trim(),
                    Integer.parseInt(txtNroHab_update.getText().trim()),
                    cbTipoHab_update.getSelectedItem().toString(),
                    Double.parseDouble(txtPrecioHab_update.getText().trim()),
                    entrada,
                    salida
            );

            if (Reserva.actualizarReserva(r)) {
                JOptionPane.showMessageDialog(this, "Reserva actualizada correctamente.");
                bloquearCamposUpdate();
                limpiarCamposUpdate();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar la reserva.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnActualizar_updateActionPerformed

    private void btnRegistrar_crear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar_crear1ActionPerformed
        String dni = txtDNI_delete.getText().trim();

        if (dni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un DNI.");
            return;
        }

        Reserva r = Reserva.buscarPorDNI(dni);

        if (r == null) {
            JOptionPane.showMessageDialog(this, "No existe una reserva con ese DNI.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de que deseas eliminar esta reserva?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            boolean eliminado = Reserva.eliminarPorDNI(dni);

            if (eliminado) {
                JOptionPane.showMessageDialog(this, "Reserva eliminada correctamente.");
                txtDNI_delete.setText("");
                // Opcional: refrescar la tabla
                Reserva.listarReservas(tablaHuesped);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar la reserva.");
            }
        }
    }//GEN-LAST:event_btnRegistrar_crear1ActionPerformed

    private void cbTipoHab_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoHab_crearActionPerformed
        double precio = 0.0;
        switch (cbTipoHab_crear.getSelectedItem().toString()) {
            case "HABITACION INDIVIDUAL":
                precio = 85.90;
                break;
            case "HABITACION DOBLE":
                precio = 105.90;
                break;
            case "HABITACION TRIPLE":
                precio = 125.90;
                break;
            case "HABITACION CUADRUPLE":
                precio = 145.90;
                break;
            case "HABITACION SUITE":
                precio = 200.90;
                break;
            case "HABITACION PRESIDENCIAL":
                precio = 1250.90;
                break;
        }
         txtPrecioHab_crear.setText(String.format("%.2f", precio));
         txtPrecioHab_crear.setEnabled(false);

    }//GEN-LAST:event_cbTipoHab_crearActionPerformed

    private void cbTipoHab_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoHab_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoHab_updateActionPerformed
    
    private void limpiarCamposUpdate() {
        txtDNI_update.setText("");
        txtNombre_update.setText("");
        txtApePater_update.setText("");
        txtApeMat_update.setText("");
        txtCorreo_update.setText("");
        txtNumTel_update.setText("");
        txtNroHab_update.setText("");
        txtPrecioHab_update.setText("");
        cbTipoHab_update.setSelectedIndex(0);
    }

    private void habilitarCamposUpdate() {
        txtNombre_update.setEnabled(true);
        txtApePater_update.setEnabled(true);
        txtApeMat_update.setEnabled(true);
        txtCorreo_update.setEnabled(true);
        txtNumTel_update.setEnabled(true);
        txtNroHab_update.setEnabled(true);
        cbTipoHab_update.setEnabled(true);
        txtPrecioHab_update.setEnabled(true);
        btnActualizar_update.setEnabled(true);
    }

    // Método auxiliar para limpiar campos después de registrar
    private void limpiarCamposCrear() {
        txtDNI_crear.setText("");
        txtNombre_crear.setText("");
        txtApePater_crear.setText("");
        txtApeMat_crear.setText("");
        txtCorreo_crear.setText("");
        txtNumTel_crear.setText("");
        txtNroHab_crear.setText("");
        txtPrecioHab_crear.setText("");
        cbTipoHab_crear.setSelectedIndex(0);
        txtDNI_crear.requestFocus();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar_update;
    private javax.swing.JButton btnBuscar_update;
    private javax.swing.JButton btnBuscar_update1;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnRegistrar_crear;
    private javax.swing.JButton btnRegistrar_crear1;
    private javax.swing.JComboBox<String> cbTipoHab_crear;
    private javax.swing.JComboBox<String> cbTipoHab_update;
    private com.toedter.calendar.JDateChooser dcEntrada;
    private com.toedter.calendar.JDateChooser dcEntrada_update;
    private com.toedter.calendar.JDateChooser dcSalida;
    private com.toedter.calendar.JDateChooser dcSalida_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblUsuarioName;
    private javax.swing.JTable tablaHuesped;
    private javax.swing.JTextField txtApeMat_crear;
    private javax.swing.JTextField txtApeMat_update;
    private javax.swing.JTextField txtApePater_crear;
    private javax.swing.JTextField txtApePater_update;
    private javax.swing.JTextField txtCorreo_crear;
    private javax.swing.JTextField txtCorreo_update;
    private javax.swing.JTextField txtDNI_crear;
    private javax.swing.JTextField txtDNI_delete;
    private javax.swing.JTextField txtDNI_update;
    private javax.swing.JTextField txtNombre_crear;
    private javax.swing.JTextField txtNombre_update;
    private javax.swing.JTextField txtNroHab_crear;
    private javax.swing.JTextField txtNroHab_update;
    private javax.swing.JTextField txtNumTel_crear;
    private javax.swing.JTextField txtNumTel_update;
    private javax.swing.JTextField txtPrecioHab_crear;
    private javax.swing.JTextField txtPrecioHab_update;
    // End of variables declaration//GEN-END:variables
}
